### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AleksanderBoldyrev**

### CODE REVIEW

**Comment by SemenMartynov** [comment]
@AleksanderBoldyrev this repo is already in the list, as i see...

**Comment by AleksanderBoldyrev** [comment]
As I see, it is not, and the pull request isnot merged, so I can't guess, what is the problem with my pr...

**Comment by AleksanderBoldyrev** [comment]
Or am I mistaking? because there was no issue for my task, so I'm in doubts...

**Comment by SemenMartynov** [comment]
https://raw.githubusercontent.com/SemenMartynov/SPbPU_TRPO_2017/master/README.md
the fourth one

**Comment by AleksanderBoldyrev** [comment]
Now I see, thank you... will be there any issue today for the gradle task?

**Pull request closed without merging**
