### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Yehuk**
Added link to my repository.

### CODE REVIEW

**Comment by SemenMartynov** [comment]
I have seen this work several times already

**Comment by Yehuk** [comment]
Should I rewrite it?

**Comment by SemenMartynov** [comment]
Of course! It should be YOUR work, not someone else's...

**Comment by Yehuk** [comment]
Ok, but I will not be able to check if it works because I can't use Docker neither on my Windows 8 nor Debian on my Virtual Machine.

**Comment by SemenMartynov** [comment]
I don't see any reason why you can't use Docker on Windows or Debian Linux.
- https://docs.docker.com/docker-for-windows/
- https://docs.docker.com/engine/installation/linux/docker-ce/debian/

**Comment by Yehuk** [comment]
Well, installer for Windows says that Docker is only for Windows 10. And I didn't know that  Docker CE counts as Docker.

**Comment by SemenMartynov** [comment]
We discussed this question at the first seminar.

**Comment by Yehuk** [comment]
I rewrited validator and tested it through Docker. Everything works fine now.

**Pull request merged**
